"""Initial migration

Revision ID: 6ab72ed9a254
Revises: a30461b795fe
Create Date: 2025-02-17 00:38:09.886000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ab72ed9a254'
down_revision: Union[str, None] = 'a30461b795fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_fileinfo_id'), 'fileinfo', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fileinfo_id'), table_name='fileinfo')
    # ### end Alembic commands ###
