"""Initial migration

Revision ID: a30461b795fe
Revises:
Create Date: 2023-10-01 12:34:56.789012

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel  # Добавьте этот импорт

# revision identifiers, used by Alembic.
revision = 'a30461b795fe'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fileinfo',
        sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('file_type', sa.String(), nullable=False),
        sa.Column('file_size', sa.Integer(), nullable=False),
        sa.Column('file_path', sa.String(), nullable=False),
        sa.Column('upload_time', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fileinfo')
    # ### end Alembic commands ###
